### ISSUE TITLE
How to create D_offline for a new gym environment?

### ISSUE THREAD

**Issue by Lplenka** [abalakrishna123/recovery-rl#2]
Hello @abalakrishna123 

I gathered from your paper [Recovery RL: Safe Reinforcement Learning with Learned Recovery Zones](https://arxiv.org/pdf/2010.15920.pdf) that Recovery RL follows these three steps:

1. Generate offline data D<sub>offline</sub> which contain constraint violations. 
2. Train safety critic Q<sup>$\Pi$</sup><sub>risk</sub> using D<sub>offline</sub> through [qrisk.py](https://github.com/abalakrishna123/recovery-rl/blob/master/recovery_rl/qrisk.py).
3.  Train the recovery RL that trains forward policy and recovery policy using trained safety critic through [SAC.py](https://github.com/abalakrishna123/recovery-rl/blob/master/recovery_rl/sac.py) 

How can I get the D<sub>offline</sub> data for a custom gym environment?

Looking forward to your suggestion. Thanks :)

**Comment by abalakrishna123** [comment]
How you collect this offline data will largely be based on the environment. We describe how we did this for our environments in the Offline Data Collection section of the paper. In general, the main challenge is you probably want constraint violation examples that are in the neighborhood of states you might actually visit when doing the task. A couple of techniques that might help you collect such examples are to (1) design a demonstrator and add noise to it so it starts violating constraints in task relevant areas, (2) train an unconstrained RL policy for the task and use it collect examples of constraint violations, or (3) train an unconstrained RL policy for the task and add an additional term to actually reward it for violating constraints.

**Comment by Lplenka** [comment]
@abalakrishna123  Thanks for your response. I will work on generating the offline data. I am assuming that D<sub>offline</sub> looks something like this:

```
<N x [obs, action]>
```

Where 
- N is the number of transitions
-  obs is the observation 
- action is the action taken by the agent after observing "obs"

I downloaded the recovery_rl_data folder, which contains the offline data for environments used in the paper.

- recovery_rl_data/demos/maze 
        -  constraint_demo_rollouts.pkl - shape (500, 20, 5)
        - constraint_demos.pkl - shape (10000, 5)

Could you please explain which one is offline data for the maze environment? why two files?

Why do only extraction env folders have task_demo.pkl ?

**Comment by Lplenka** [comment]
One more doubt, in [experiment.py](https://github.com/abalakrishna123/recovery-rl/blob/master/recovery_rl/experiment.py) line [77](https://github.com/abalakrishna123/recovery-rl/blob/master/recovery_rl/experiment.py#L77) you are getting the offline data

```
self.constraint_demo_data, self.task_demo_data, self.obs_seqs, self.ac_seqs, self.constraint_seqs = self.get_offline_data()
```

However, I observed that in the function definition of `self.get_offline_data()`, not all of these objects are created; some remain empty. Action sequences `ac_seqs` is only returned for "Image maze", not for other environments; why so?

This might be a silly question, I am just trying to wrap my head around the code. 

Thanks for your patience in answering my queries.

**Comment by abalakrishna123** [comment]
Hi, sorry for the confusing code here. ac_seqs (and also obs_seqs and constraint_seqs) is only returned for Image Maze since for this environment, we train a visual dynamics model that requires contiguous chunks of observations and actions (ie. o_1, a_1, o_2, a_2, ...). For all other environments, we just train a 1-step dynamics model where o_{t+1} = f(o_t, a_t) so we do not require observations and actions to be from contiguous trajectories.
